/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fragment_gaolei_jniapplication_JniUtils */

extern "C" {
#endif
/*
 * Class:     com_fragment_gaolei_jniapplication_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fragment_gaolei_jniapplication_JniUtils_getStringFormC
        (JNIEnv *env, jclass object) {
    return (*env)->NewStringUTF(env, "这里是来自c的string");
}
}
#ifdef __cplusplus
}
#endif
#endif
